name: CI/CD

on: [push, pull_request]

jobs:
  test_build_release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Install pytemplates
      run: poetry install

    - name: Run tests and collect coverage
      run: poetry run pytest

    - name: Write a JSON coverage report
      run: poetry run coverage json

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: crabtr26/pytemplates

    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
